task:
  matrix:
  - name: FreeBSD Build
    freebsd_instance:
      image_family: freebsd-13-1
    environment:
      - GITHUB_TOKEN: ENCRYPTED[38a5a4b83d9859dccc98655bdc993fb9da11ad43d0c787473b692f45732505f167335e45564474e9f3a1cbe7a883b3ae]
      - JUKA_TOKEN: Unix_Amd64
    setup_script:
    - pkg install -y wget bash libunwind icu libuv boost-libs gdb libffi wget bash encodings glib gnutls libarchive libuv
    - sudo mkdir /dotnet
    - wget https://github.com/sec/dotnet-core-freebsd-source-build/releases/download/6.0.400/dotnet-sdk-6.0.400-freebsd-x64.tar.gz
    - sudo tar xf dotnet-sdk-6.0.400-freebsd-x64.tar.gz -C /dotnet/
    - wget https://github.com/sec/dotnet-core-freebsd-source-build/releases/download/6.0.400/Microsoft.AspNetCore.App.Runtime.freebsd-x64.6.0.8.nupkg
    - wget https://github.com/sec/dotnet-core-freebsd-source-build/releases/download/6.0.400/Microsoft.NETCore.App.Runtime.freebsd-x64.6.0.8.nupkg
    - sudo mv *.nupkg /dotnet/
    script:
    - cd src
    - /dotnet/dotnet nuget add source /dotnet/
    - /dotnet/dotnet restore
    - /dotnet/dotnet test
    package_script:
    - /dotnet/dotnet publish /tmp/cirrus-ci-build/src/Juka.sln -c release --self-contained true -a "" /p:Version=${CIRRUS_TAG}
    - tar -czf Juka_Unix_Amd64_${CIRRUS_TAG}.tar.gz -C /tmp/cirrus-ci-build/src/Juka/bin/Release/net6.0/freebsd-x64/publish .
    - tar -czf JukaAPI_Unix_Amd64_${CIRRUS_TAG}.tar.gz -C /tmp/cirrus-ci-build/src/JukaApi/bin/Release/net6.0/freebsd-x64/publish .
    - chmod 777 *.sh
    - ./publish.sh
  - name: Linux Build
    container:
      image: ubuntu:latest
    environment:
      - GITHUB_TOKEN: ENCRYPTED[38a5a4b83d9859dccc98655bdc993fb9da11ad43d0c787473b692f45732505f167335e45564474e9f3a1cbe7a883b3ae]
      - JUKA_TOKEN: Linux_X86
    setup_script:
    - dpkg --add-architecture i386
    - apt-get update
    - apt-get install -y wget curl libc6:i386 libncurses5:i386 libstdc++6:i386 libicu-dev:i386 libssl-dev:i386 zlib1g:i386 
    - mkdir /usr/share/dotnet
    - wget https://github.com/Servarr/dotnet-linux-x86/releases/download/v6.0.8-52/dotnet-sdk-6.0.400-linux-x86.tar.gz
    - tar xf dotnet-sdk-6.0.400-linux-x86.tar.gz -C /usr/share/dotnet/
    - wget https://github.com/Servarr/dotnet-linux-x86/releases/download/v6.0.8-52/Microsoft.AspNetCore.App.Runtime.linux-x86.6.0.8.nupkg
    - wget https://github.com/Servarr/dotnet-linux-x86/releases/download/v6.0.8-52/Microsoft.NETCore.App.Runtime.linux-x86.6.0.8.nupkg
    - mv *.nupkg /usr/share/dotnet/
    script:
    - cd src
    - /usr/share/dotnet/dotnet nuget add source /usr/share/dotnet/
    - /usr/share/dotnet/dotnet restore
    - /usr/share/dotnet/dotnet test
    package_script:
    - /usr/share/dotnet/dotnet publish /tmp/cirrus-ci-build/src/Juka.sln -c release --self-contained true --runtime linux-x86 /p:Version=${CIRRUS_TAG}
    - tar -czf Juka_Linux_X86_${CIRRUS_TAG}.tar.gz -C /tmp/cirrus-ci-build/src/Juka/bin/Release/net6.0/linux-x86/publish .
    - tar -czf JukaAPI_Linux_X86_${CIRRUS_TAG}.tar.gz -C /tmp/cirrus-ci-build/src/JukaApi/bin/Release/net6.0/linux-x86/publish .
    - pwd
    - chmod +x ./publish.sh
    - ./publish.sh