image: Visual Studio 2022
before_build: 
  - cd src
  - dotnet restore
  - dotnet test

build: 
  project: src/Juka.sln

skip_tags: false
artifacts:
- path: 'src\JukaAzureFunction\bin\Release'
  name: Juka_$(APPVEYOR_BUILD_VERSION)
  type: zip
configuration:
- Release