image: Visual Studio 2022

branches:
  # whitelist
  only:
    - master

skip_tags: false
skip_non_tags: false

before_build: 
  - cd src
  - dotnet restore
  - dotnet test

build: 
  project: src/Juka.sln

configuration:
- Release

artifacts:
- path: 'src\JukaAzureFunction\bin\Release'
  name: Juka_$(APPVEYOR_BUILD_VERSION)
  type: zip


deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: Juka_$(APPVEYOR_BUILD_VERSION)    
    auth_token:
      secure: XCqLJKrsMnRCCEEcsPL53Emba/2GrP172INtXx86eu5XBbed614ug/2dcx8MZwmr
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: false       # deploy on tag push only