image: Visual Studio 2017
before_build: 
  - cd DReAM
  - "nuget restore"
  - cd ../DreamCompiler/dreamCompiler
  - ./build.bat
build: 
  project: DReAM/DReAM.sln
notifications: 
  - 
    incoming_webhook: "https://hooks.slack.com/services/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"
    provider: Slack
skip_tags: false
artifacts:
- path: '**'
  name: DReAM_$(APPVEYOR_BUILD_VERSION)
  type: zip
configuration:
- Release

after_build:
  - dir /s