image: Visual Studio 2022

branches:
  # whitelist
  only:
    - master

skip_tags: true
skip_non_tags: false

version: '0.0.{build}'

environment:
  token:
    secure: YPPyzDbCboQKYOfAl/4XahyYfDiWOsyjoL2WjyNOxH4=

assembly_info:
  patch: true
  file: 'src\**\AssemblyInfo.*' 
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'

dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj; **\*.csproj'
  version: '{version}'
  package_version: $(APPVEYOR_BUILD_VERSION)
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build: 
 - ps: |
        $env:MY_XT= $env:APPVEYOR_REPO_COMMIT_MESSAGE
        if ($env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
        {
        $env:MY_XT="$($env:APPVEYOR_REPO_COMMIT_MESSAGE) \n $($env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)"
        }
 - cd src
 - dotnet test

after_build:
 - dotnet publish -c Release --self-contained true --runtime osx-x64 Juka 
 - dotnet publish -c Release --self-contained true --runtime osx-x64 JukaApi 

 - dotnet publish -c Release --self-contained true --runtime linux-x64 Juka
 - dotnet publish -c Release --self-contained true --runtime linux-x64 JukaApi

 - dotnet publish -c Release --self-contained true --runtime linux-arm Juka 
 - dotnet publish -c Release --self-contained true --runtime linux-arm JukaApi

 - dotnet publish -c Release --self-contained true --runtime linux-arm64 Juka
 - dotnet publish -c Release --self-contained true --runtime linux-arm64 JukaApi 

 - dotnet publish -c Release --self-contained true --runtime win-x86 Juka 
 - dotnet publish -c Release --self-contained true --runtime win-x86 JukaApi

 - dotnet publish -c Release --self-contained true --runtime win-x64 Juka 
 - dotnet publish -c Release --self-contained true --runtime win-x64 JukaApi 

 - dotnet publish -c Release --self-contained true --runtime win-arm64 Juka 
 - dotnet publish -c Release --self-contained true --runtime win-arm64 JukaApi 

 - dotnet pack --nologo -c Release JukaCompiler

 - dotnet publish -c Release JukaAzureFunction



configuration: Release

artifacts:
- path: 'src\Juka\bin\Release\net6.0\win-x86\publish'
  name: Juka_Windows_X86_$(APPVEYOR_BUILD_VERSION)
  type: zip
- path: 'src\Juka\bin\Release\net6.0\win-x64\publish'
  name: Juka_Windows_Amd64_$(APPVEYOR_BUILD_VERSION)
  type: zip
- path: 'src\Juka\bin\Release\net6.0\win-arm64\publish'
  name: Juka_Windows_Arm64_$(APPVEYOR_BUILD_VERSION)
  type: zip

- path: 'src\Juka\bin\Release\net6.0\osx-x64\publish'
  name: Juka_MacOS_Amd64_$(APPVEYOR_BUILD_VERSION)
  type: zip

- path: 'src\Juka\bin\Release\net6.0\linux-x64\publish'
  name: Juka_Linux_Amd64_$(APPVEYOR_BUILD_VERSION)
  type: zip
- path: 'src\Juka\bin\Release\net6.0\linux-arm\publish'
  name: Juka_Linux_Arm_$(APPVEYOR_BUILD_VERSION)
  type: zip
- path: 'src\Juka\bin\Release\net6.0\linux-arm64\publish'
  name: Juka_Linux_Arm64_$(APPVEYOR_BUILD_VERSION)
  type: zip



- path: 'src\JukaApi\bin\Release\net6.0\win-x86\publish'
  name: JukaAPI_Windows_X86_$(APPVEYOR_BUILD_VERSION)
  type: zip
- path: 'src\JukaApi\bin\Release\net6.0\win-x64\publish'
  name: JukaAPI_Windows_Amd64_$(APPVEYOR_BUILD_VERSION)
  type: zip
- path: 'src\JukaApi\bin\Release\net6.0\win-arm64\publish'
  name: JukaAPI_Windows_Arm64_$(APPVEYOR_BUILD_VERSION)
  type: zip

- path: 'src\JukaApi\bin\Release\net6.0\osx-x64\publish'
  name: JukaAPI_MacOS_Amd64_$(APPVEYOR_BUILD_VERSION)
  type: zip

- path: 'src\JukaApi\bin\Release\net6.0\linux-x64\publish'
  name: JukaAPI_Linux_Amd64_$(APPVEYOR_BUILD_VERSION)
  type: zip
- path: 'src\JukaApi\bin\Release\net6.0\linux-arm\publish'
  name: JukaAPI_Linux_Arm_$(APPVEYOR_BUILD_VERSION)
  type: zip
- path: 'src\JukaApi\bin\Release\net6.0\linux-arm64\publish'
  name: JukaAPI_Linux_Arm64_$(APPVEYOR_BUILD_VERSION)
  type: zip

- path: 'src\JukaCompiler\bin\Release\net6.0\'
  name: Juka_Compiler_dll_$(APPVEYOR_BUILD_VERSION)
  type: zip

- path: 'src\JukaCompiler\bin\Release\*.nupkg'
  name: Juka_Compiler
  type: NuGetPackage

- path: 'src\JukaAzureFunction\bin\Release\net6.0\publish'
  name: Juka_Azure_Function_$(APPVEYOR_BUILD_VERSION)
  type: zip

deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.zip/
    tag: '$(APPVEYOR_BUILD_VERSION)'
    release: 'Juka v$(APPVEYOR_BUILD_VERSION)'
    description: "## 🍂 Changelog \n $(MY_XT)"
    auth_token:
      secure: XCqLJKrsMnRCCEEcsPL53Emba/2GrP172INtXx86eu5XBbed614ug/2dcx8MZwmr
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: false       # deploy on tag push only
  - provider: NuGet
    api_key:
      secure: x/4PXOtHjSV0Js8178xYZ+smiBELpwlYbKOw13d8r4tFWt9HFG/ln+vGOLvTstE3
    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: false       # deploy on tag push only

after_deploy:
 - ps: $headers = @{}
 - ps: $headers['Authorization'] = "Bearer $env:token"
 - ps: $headers["Content-type"] = "application/json"
 - ps: $dbinar = @{}
 - ps: $dbinar["accountName"] = 'TheAndreiM'
 - ps: $dbinar["projectSlug"] = 'juka-webassembly'
 - ps: $dbinar["branch"] = 'main'
 - ps: $dbinar["environmentVariables"] = @{}
 - ps: $bod = $dbinar | ConvertTo-json
 - ps: Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/builds' -Headers $headers -Method POST -body $bod
 - ps: $headers = @{}
 - ps: $headers['Authorization'] = "Bearer $env:token"
 - ps: $headers["Content-type"] = "application/json"
 - ps: $dbinar = @{}
 - ps: $dbinar["accountName"] = 'TheAndreiM'
 - ps: $dbinar["projectSlug"] = 'jukaApp'
 - ps: $dbinar["branch"] = 'master'
 - ps: $dbinar["environmentVariables"] = @{}
 - ps: $bod = $dbinar | ConvertTo-json
 - ps: Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/builds' -Headers $headers -Method POST -body $bod