---
name: EthicalCheck-Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 21 6 * * 2
  workflow_dispatch: null
permissions:
  contents: read
jobs:
  Trigger_EthicalCheck:
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: EthicalCheck  Free & Automated API Security Testing Service
        uses: apisec-inc/ethicalcheck-action@main
        with:
          oas-url: https://api.jukalang.com/v1/swagger.json
          email: sec@jukalang.com
          sarif-result-file: ethicalcheck-results.sarif
      - name: Upload sarif file to repository
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./ethicalcheck-results.sarif
